### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by kyrrr** [brunobraga/termsaver#34]
System: macOS 10.15

Command: ```pip3 install termsaver```

Expected result: ```cool screensavers```

Actual result: 

Installer falls over while trying thank me

```
Downloading https://files.pythonhosted.org/packages/9a/b0/4428c151d94b5358dd92b92c045cd40b448ff65a37b994ecb7252ad559f8/termsaver-0.4.tar.gz (46kB)
     |████████████████████████████████| 51kB 1.1MB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c7/vx918ndx0v3g_j49c1tf4_8w0000gn/T/pip-install-x0k8wubc/termsaver/setup.py", line 103
        """
          ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("""
    Thank you for trying termsaver.
    """)?
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/c7/vx918ndx0v3g_j49c1tf4_8w0000gn/T/pip-install-x0k8wubc/termsaver/
```

**Comment by brunobraga** [comment]
Unfortunately I have never ported the code for python 3. It should work if you call pip instead of pip3 (make sure pip is python 2).

This is also documented in the project readme by the way.

If anyone is interested in updating this project to support python 3, I'd appreciate the help.
