### ISSUE TITLE
Cant install termsaver, issue with setup.py

### ISSUE THREAD

**Issue by kylepollina** [brunobraga/termsaver#54]
Hello, I am having trouble installing termsaver. Currently on macos, getting this error:
```
$ pip install termsaver 
Collecting termsaver
  Downloading termsaver-0.4.tar.gz (46 kB)
     |████████████████████████████████| 46 kB 3.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/kylepollina/d3/app/smart-search/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/qr/b30k7lmx2fsf4cdzr371yn_w0000gp/T/pip-install-3l5etrka/termsaver/setup.py'"'"'; __file__='"'"'/private/var/folders/qr/b30k7lmx2fsf4cdzr371yn_w0000gp/T/pip-install-3l5etrka/termsaver/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/qr/b30k7lmx2fsf4cdzr371yn_w0000gp/T/pip-pip-egg-info-m3ppf9mu
         cwd: /private/var/folders/qr/b30k7lmx2fsf4cdzr371yn_w0000gp/T/pip-install-3l5etrka/termsaver/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qr/b30k7lmx2fsf4cdzr371yn_w0000gp/T/pip-install-3l5etrka/termsaver/setup.py", line 101
        print """
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(""")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I think something is wrong with the current setup file on pypi?

**Comment by brunobraga** [comment]
This is due to version 3 support. There is an update in the source for that, but not released to PIP.
A couple of options:
- download the source and compile it using "python setup.py install"
- use Python2 to install it (pip2 or whatever it points to in your distro)

Apologies for the trouble, this is supposed to be up already, needing some help to get the last bits finalised.

**Comment by EddieDover** [comment]
@kylepollina pip support is coming very shortly. Testing has gone smoothly and I should have a PR up soon that will lift the code so you can either install from pip or build from source. I'll tag this issue when it's ready.
