### ISSUE TITLE
asciiartfarts is offline

### ISSUE THREAD

**Issue by antanariva** [brunobraga/termsaver#70]
termsaver.asciiartfarts: Connecting to http://www.asciiartfarts.com/random.cgi ... (this could take a while)
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/termsaver/termsaverlib/screen/helper/urlfetcher.py", line 172, in fetch
    resp = urlopen(req)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/termsaver", line 8, in <module>
    sys.exit(entryPoint())
  File "/usr/local/lib/python3.10/dist-packages/termsaver/__init__.py", line 129, in entryPoint
    screen(parser=parser)._parse_args()
  File "/usr/local/lib/python3.10/dist-packages/termsaver/termsaverlib/screen/asciiartfarts.py", line 110, in _parse_args
    self.autorun()
  File "/usr/local/lib/python3.10/dist-packages/termsaver/termsaverlib/screen/base/__init__.py", line 239, in autorun
    self._run_cycle()
  File "/usr/local/lib/python3.10/dist-packages/termsaver/termsaverlib/screen/asciiartfarts.py", line 99, in _run_cycle
    new_text = self.process_data(self.fetch(self.url)).decode("utf-8")
  File "/usr/local/lib/python3.10/dist-packages/termsaver/termsaverlib/screen/helper/urlfetcher.py", line 177, in fetch
    raise exception.UrlException(uri,
termsaver.termsaverlib.exception.UrlException: Could not fetch URL, because [Errno -3] Temporary failure in name resolution

**Comment by EddieDover** [comment]
The domain/url is currently unavailable, which is causing the error.

If it doesn't resolve itself soon, I'll remove asciiartfarts from the screens list.

**Comment by brunobraga** [comment]
This was doomed to happen st some point. As an alternative you can use the feeds screen and point to another valid location.

I’d suggest we try to reach out to the owner (if available) and remove the screen if no plans to be supported anymore.

**Comment by EddieDover** [comment]
It seems the site is restored. Closing this as resolved for now.
